name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
        script: |
          cd /var/www/api.wizuh.de
          git pull origin main
          composer install --no-interaction --prefer-dist  # Ponovna instalacija paketa na serveru
          php artisan migrate --force  # Pokretanje migracija na serveru
          php artisan config:cache  # Opcionalno, ako želite očistiti cache
          php artisan route:cache  # Opcionalno, ako želite cache rute
