name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
        script: |
          cd /var/www/api.wizuh.de
          git pull origin main
          # Dodaj bilo koju komandu za restarte servera ili druge komande koje trebaš
